### ISSUE TITLE
glue together the SCHEME://DOMAIN/PATH?QUERY in access log and syslog

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1006]
currently these are separated by spaces

**Comment by ea-at-diladele-com** [comment]
if we save url and referrer , we should not use store_path and store_query as parameters in the monitorin.json, it does not make much sense.

they should be changed to store_url and store_referer . I already did this for the wsmgr part. please correct the gui. thank you!

**Comment by ra-at-diladele-com** [comment]
Every channels stores the same information - the syslog and access log will always need to store URL an Referer like other channels to - it is only possible to exclude 'path' and 'query'  both in URL and Referer from storing to keep the amount of log within limits.

Please:
- remove 'StoreUrl' and 'StoreReferer' from Modules config struct
- reimplement ToLogString to glue together scheme://domain/path?query for access.log and syslog if this is requred.

**Comment by ea-at-diladele-com** [comment]
now, should be as you specified. there are still some unknowns which are described in a separate email.

**Comment by ra-at-diladele-com** [comment]
ok
