### ISSUE TITLE
wsmgrd - log by default is too verbose

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1011]
we need to move some records to DEBUG level (like how much time it took to upload a file)

**Comment by ea-at-diladele-com** [comment]
this should be done now. we should also add the level in the command line => it should be passed from the bootstrapper.

right now we show everything including debug. Please test current behavior and reassign to me when we should control the debug level thru command line.

Thank you!

**Comment by ra-at-diladele-com** [comment]
In monitor.json there is a setting now:
```
 "logging": 1
```

where possible values are:
```
WSMGRD_LOG_DEBUG   = 0
WSMGRD_LOG_INFO    = 1
WSMGRD_LOG_WARN    = 2
WSMGRD_LOG_ERROR   = 3
```

Please implement setting of log level in wsmgrd.exe based on the value in monitor.json. if the value is incorrect it should be 1, i.e. info.

**Comment by ea-at-diladele-com** [comment]
not clear. why is this in monitoring.json? should not this be in wsmgr.settings? similar to rest service port? this is not really a "monitoring" functionality. Thank you!

**Comment by ea-at-diladele-com** [comment]
done, please test.

**Comment by ra-at-diladele-com** [comment]
need to live in wsmgr.settings

**Comment by ra-at-diladele-com** [comment]
done in Web UI - need to test
