### ISSUE TITLE
wsmgrd cannot be started if MySQL is not running

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1023]
- intergrate wsmgr with mysql
- start mysql
- start wsmgr - everything is fine
- stop mysql
- restart wsmgrd - it cannot be started error below
expected - wsmgrd is started and periodically tries to reconnect to MySQL database

```
2015/10/07 20:43:01 Driver name 'mysql'
2015/10/07 20:43:01 Data source name 'root:Passw0rd@tcp(127.0.0.1:3306)/qlproxy_monitor?autocommit=0&innodb_support_xa=0'
2015/10/07 20:43:01 Error starting the modules: dial tcp 127.0.0.1:3306: connection refused
```

**Comment by ea-at-diladele-com** [comment]
should be fixed now. please test.
