### ISSUE TITLE
Try builiding on NetBSD (how to package??)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1065]

**Comment by ea-at-diladele-com** [comment]
It has a separate package system which is similar to FreeBSD but still different. Absolutely different from FreeBSD 10, so it will require more efforts to support it, especially if we are switching only to the latest freebsd.

Currently we can compile the product on netbsd platform with go 1.5. Let's discuss what should be our next steps regarding this platform.

**Comment by ra-at-diladele-com** [comment]
Pending...
