### ISSUE TITLE
Try to redo the pfSense tutorial for pfSense 2.3 and qlproxy 4.3

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1066]
http://docs.diladele.com/tutorials/filtering_https_traffic_squid_pfsense/index.html

**Comment by ea-at-diladele-com** [comment]
Could you please be more specific? pfSense 2.3 does not exist, does it? The latest version is 2.2.4 if I'm not mistaken.

**Comment by ra-at-diladele-com** [comment]
Yes latest is 2.2 sorry

**Comment by ea-at-diladele-com** [comment]
Documentation for Freebsd10 and pfsense 2.2.4 is updated, but there are still some bugs in the pfSense installation, even though the basic filtering/https works fine. Communicated offline.

**Comment by ra-at-diladele-com** [comment]
- Dashboard gives following Error message:
- Realtime monitoring does not open, it gives the following error: Gateway timeout, The gateway did not receive a timely response from the upstream server or application

Restarting qlproxy at command line gives the following error at the start:
```
[2.2.5-RELEASE] /opt/qlproxy/bin: sh restart.sh
restarting Web Safety Manager...
wsmgrd not running? (check /opt/qlproxy/var/run/wsmgrw.pid).
Starting wsmgrd.
main - fatal exception, error: main: can not flock the pid filere starting Web Safety ICAP daemon...
Stopping qlproxyd.
```
