### ISSUE TITLE
Need search engine word detector (in 4.5?)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1140]
Finally we need to have the strings use typed into search box of a search engine (as google) in reports. But - the request needs to be allowed - i.e. ICAP server reports it as clean. 

It is possible to have such request logged into the database - but it requires to enable "store every verdict" feature. This would save so  much info about clean objects!!! 

We need to think out something - like additional analysis  of a record (store/throw away) in the wsmgrd? It is not right to add a new "log_only" verdict into the filtering engine as it ruins the clear and concise logic inside...

See the request:

```
We've been asked to log pupil activity by a list of keywords but ​not ​​necessarily 
block the​m​. The goal here is for the UK schools to meet the new requirements 
around protecting them from radicalisation.
See ​http://www.bbc.co.uk/news/uk-35157910
```

**Comment by ra-at-diladele-com** [comment]
for 4.4 we have this report and it should work even for "clean" records. In 4.5 we will try to understand how to store less in db..

**Comment by ea-at-diladele-com** [comment]
Is this really a problem? Do we store to much in db currently?

**Comment by ra-at-diladele-com** [comment]
It is on 4.8 - let's think then

**Comment by ra-at-diladele-com** [comment]
done already; closing
