### ISSUE TITLE
Detailed Domain Report for facebook - need to limit drill down entries

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1146]
currently number of records in drill down is not limited - then for example list of URL paths for current database - 41 K lines. This kills the browser!

We need to limit the number of lines to 100 in any drill down ???

**Comment by ea-at-diladele-com** [comment]
need to test

**Comment by ra-at-diladele-com** [comment]
tested and output is limited; closing bug
