### ISSUE TITLE
Resolve IP to Domain Name does not work when importing monitoring records?

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1148]

**Comment by ra-at-diladele-com** [comment]
Is this functionality present?

**Comment by ea-at-diladele-com** [comment]
could you provide more context? on insert the username is "-", ip 8 8 8 8 
in the db I see google-public-dns-a.google.com.  r u sure you have the corresponding flag as "true" in the monitor config?

**Comment by ea-at-diladele-com** [comment]
or is this about domain names - should there be check that domain name is not an ip address?

**Comment by ea-at-diladele-com** [comment]
what should be the expected values of db host and tld in the following cases 
if incoming host and url contain
`117.22.252.216` and
`117.22.252.216:8888`

**Comment by ra-at-diladele-com** [comment]
No this is NOT for domain name. This is for IP -> artificial User name conversion.
I will test now.

**Comment by ra-at-diladele-com** [comment]
It works, sorry was incorrect reverse DNS configuration
