### ISSUE TITLE
add to Web UI - icap-users-search-queries report

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1149]
parameters - user_list if not empty then report gets generated for given users - other wise for all

**Comment by ra-at-diladele-com** [comment]
added to template_list, need to also specify parameters

**Comment by ra-at-diladele-com** [comment]
done in latest build, please test if works correctly

**Comment by ea-at-diladele-com** [comment]
test
