### ISSUE TITLE
Persistent Sink Monitor DB *MUST* purge data before insert as indicated in monitor.json

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1154]
"persistent" {
   "purge" : 30
}

**Comment by ea-at-diladele-com** [comment]
"persistent": {
        "purge": 30,
        "purge_schedule": {
            "dom": "*",
            "dow": "*",
            "hour": "1",
            "min": "4",
            "month": "*"
        }, 

should call database from bin

**Comment by ea-at-diladele-com** [comment]
need to test
