### ISSUE TITLE
Drill down by URL

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1156]
in output urls.JSON we have tld + path + query. This is not enough to reconstruct actual URL that the client requested. We also need to have the host. In the case we can reconstruct the actual URL as:

host + path + ? + query

Could you please take a look?

**Comment by ea-at-diladele-com** [comment]
need to test.

**Comment by ra-at-diladele-com** [comment]
Seems to work
