### ISSUE TITLE
Need to ignore shedule of type '* * * * * *' in wsmgrd sheduler

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1159]
Otherwise task is to be looping?

**Comment by ra-at-diladele-com** [comment]
In GUI this is not possible to add but through admin ui well

**Comment by ea-at-diladele-com** [comment]
we issue a warning to the log now during scheduling and assign 0 as minutes and hours in this case  (executed at 00:00 everyday)

**Comment by ea-at-diladele-com** [comment]
you have to check this in the UI - prohibit it.

**Comment by ra-at-diladele-com** [comment]
added check in UI
