### ISSUE TITLE
Need DEB package of latest 4.0 Squid in Ubuntu 14 

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1161]

**Comment by elico** [comment]
This can be done only for specific new versions of Ubuntu.
Can you list the Ubuntu versions you would like to build for?

**Comment by ra-at-diladele-com** [comment]
Hello Eliezer,
We will try first 4.0 running on Ubuntu 14 LTS. If it fails then 4.0 on 16.04 LTS.

Best regards,
Raf

**Comment by ra-at-diladele-com** [comment]
cancelled

**Comment by elico** [comment]
What was cancelled?
will it meet the 16.04 lts goal?

**Comment by ra-at-diladele-com** [comment]
Hello Eliezer,

No I meant to say the activity towards compiling Squid 4 was cancelled. We will not invest time into trying to compile it and will stay with Squid 3.5 (recompiled from Debian Testing).

Best regards,
Rafael Akchurin

Op 24 jul. 2017 om 3:49 PM heeft Eliezer Croitoru <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


What was cancelled?
will it meet the 16.04 lts goal?

**Comment by elico** [comment]
@ra-at-diladele-com Thanks.
