### ISSUE TITLE
Shall we drop real time db limit as size and have it only as N looping records 

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1180]

**Comment by ea-at-diladele-com** [comment]
I would still preserve it. Just put a limit to 50, not 10 mb. at least we have a limit if there is a need.
The monitor.json is changed, I'm not sure whether the db should be changed as well? how do you populate initial db?

**Comment by ra-at-diladele-com** [comment]
Done in UI, need to test
