### ISSUE TITLE
Describe Reports in DOCS

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1187]

**Comment by ra-at-diladele-com** [comment]
We need a general discussion of reports with short description of each report groups. 
Please also describe with screenshots how to schedule a Top Users by Requests report (step by step wizard, log view and view of actually generated report).

**Comment by ra-at-diladele-com** [comment]
Report output should be enough depersonalized.

**Comment by ea-at-diladele-com** [comment]
I think you will do it :) You are the doc guy :)
