### ISSUE TITLE
Report Scheduled for 14:00 has 13:00 generation time in meta (UTC instead of localtime?)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1199]

**Comment by ea-at-diladele-com** [comment]
it is expected. we store all data as utc, including json, it is a problem of the UI to show it correctly. I.e. if you go inside the javascript UI report, it show it correctly => it is a problem in the django table => could you fix it?

**Comment by ra-at-diladele-com** [comment]
Real Time view parses the UTC from the database. Take a look how it is done there and apply the same login in report jobs view.

**Comment by ra-at-diladele-com** [comment]
It is a hell of stupid work to parse the UTC string into time object and then make a localtime out of it - may be it is possible to write the following attributes in go:

"buildOnUTC" : <move here what is now in buildOn>
"buildOn" : <string in localtime>

???
This will let the Web UI be much easier.
