### ISSUE TITLE
icap-ips-top-by-request - click on IP, tab domains - not completely parsed domain names (domain with port)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1201]
port number should be parsed out. It is not needed.

![domain_with_port](https://cloud.githubusercontent.com/assets/2544598/13614930/1a8296dc-e573-11e5-8aa9-f9b599291b2d.png)

**Comment by ea-at-diladele-com** [comment]
this is monitoring change. please test extensively.
