### ISSUE TITLE
Shall we make this as DEBUG not INFO? in monitor log

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1203]
[2016-Mar-10 01:10:00.001] [reporting] [INFO] Successfully deserialized configuration file '/opt/qlproxy/etc/reports.json' into ...

**Comment by ea-at-diladele-com** [comment]
why don't you like it? because of the passwords or pretty-printing?
I would suggest adding pretty printing and removing the password

**Comment by ea-at-diladele-com** [comment]
but leave the info, because it will be the first thing we will require to understand what is going on

**Comment by ra-at-diladele-com** [comment]
Oke then closing the bug!
