### ISSUE TITLE
Admin must be able to override incorrectly categorized sites (as in barracude)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1252]

**Comment by sherazmughal** [comment]
there are two problem which i faced...
1. category Override is not possible
2. allowing unknown/blank categories 

Admin must be authorize for his customize change like other , TMG Surfcontrol, squidguard proxy etc etc

**Comment by sherazmughal** [comment]
How to add unknown/blank categories to other category

**Comment by sherazmughal** [comment]
we need mechanism to block uncategorized sites, majority of site don’t have categories so I cannot take risk and  add unknown/blank categories to other category

**Comment by ra-at-diladele-com** [comment]
If some domain is present in a custom category the admin must be able to say/set - 'do not look into default domain categories' this will let us use the custom categories as 'recategorization' mechanism.

**Comment by ra-at-diladele-com** [comment]
High priority for 4.6

**Comment by ra-at-diladele-com** [comment]
Not sure what can be done here. Suppose we have a domain name with assigned category 'travel'. But for us this domain is not travel but business partner. Then we either do not have do block travel category at all - (which is not desirable as travel has a lot of other sites) or we add the domain name to exclusion lists - be it global (in ICAP) or per policy.

Why to 'recategorize' it?

**Comment by sherazmughal** [comment]
custom category checked secondly, qlproxy first checked is Sites categories
and secondly Custom, we can override categories in pfsense,forefront TMGs.

like BBC is in News Category,I want to allow news category but dont want o
allow BBC so I will override/change it to custom category like "Block for
all Category".

second scenario, I want to block all "Web Base Email" except GMAIL,
therefore I want to add or Override in Custom category or other category
like News category.

final and very important thing is all Unknow categorize web site is allowed
in qlproxy and we want to block it.

**Comment by sherazmughal** [comment]
Why to 'recategorize' it?

Like.. account.google.com is in search Category and it is use for gmail login, i want to recategorize it to "WEBEMAIL"

**Comment by sherazmughal** [comment]
new Version released .....Recategorize/Custome Categories/override.......................now  possible  


custom category checked secondly, qlproxy first checked is Sites categories
and secondly Custom, we can override categories in pfsense,forefront TMGs.

like BBC is in News Category,I want to allow news category but dont want o
allow BBC so I will override/change it to custom category like "Block for
all Category".

second scenario, I want to block all "Web Base Email" except GMAIL,
therefore I want to add or Override in Custom category or other category
like News category.

final and very important thing is all Unknow categorize web site is allowed
in qlproxy and we want to block it.

**Comment by sherazmughal** [comment]
requested milestone modified

**Comment by ra-at-diladele-com** [comment]
yes we are moving to 4.7 :( too many changes in 4.6 with active directory.

**Comment by sherazmughal** [comment]
can you pl give me 4.6 final version link ..i will check
pl keep update me about 4.7

**Comment by ra-at-diladele-com** [comment]
done, need to be tested in 4.8
