### ISSUE TITLE
Incorrect Colums in Report - Bandwidth By Date

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1269]
1. Make bandwidth by date report
2. When report is ready, click on specific date
3. The tab Hours. Column names seem incorrect (mismatched column placement)

More over - overall values for IP is not correct, There cannot be 16 that's for sure...

![columns](https://cloud.githubusercontent.com/assets/2544598/14468946/7fbaeaf6-00e2-11e6-816f-79f6daa22c89.png)

**Comment by ra-at-diladele-com** [comment]
Most probably these are Hosts, TLDs, Users or so. Need to check in SQL

**Comment by ea-at-diladele-com** [comment]
should be fixed. need to test.
