### ISSUE TITLE
pfSense 2.3 is ready - need to update the tutorial

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1271]

**Comment by ra-at-diladele-com** [comment]
It is a problem now - as pfSense removed a lot of packages from 2.3 repository - including the one needed by us:

- see https://doc.pfsense.org/index.php/Installing_FreeBSD_Packages#pfSense_2.3

**Comment by ra-at-diladele-com** [comment]
Not sure what to do :(

**Comment by ra-at-diladele-com** [comment]
Back link - https://groups.google.com/d/msg/quintolabs-content-security-for-squid-proxy/NWJnf8i4MZo/gqAHzISiBgAJ

**Comment by QQHeresATissue** [comment]
As they are using nginx already is it not possible to use that?  It is installed by default, and trivially provides reverse proxying with SSL and wsgi.

**Comment by ra-at-diladele-com** [comment]
Done. Is on site at http://docs.diladele.com/tutorials/filtering_https_traffic_squid_pfsense/index.html
