### ISSUE TITLE
Apache should be SSL enabled by default

### ISSUE THREAD

**Issue by QQHeresATissue** [ra-at-diladele-com/qlproxy_external#1285]
Diladele should be HTTPS enabled by default due to the nature of data collected and monitored.  Along with username/password pairs crossing the network in plain text.  

The following can be added directly to qlproxy_virtual_host with a the key and cert files pointing to a temporary crt/key pair (this could be generated via the prereq scripts?).

    SSLEngine on
    SSLCertificateFile "/path/to/some/cert"
    SSLCertificateKeyFile "/path/to/some/key"

    SSLHonorCipherOrder on
    SSLCipherSuite HIGH:!EXPORT:!MEDIUM:!MD5:!RC4
    SSLProxyCipherSuite HIGH:!EXPORT:!MEDIUM:!MD5:!RC4
    SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
    SSLProxyProtocol all -SSLv3 -TLSv1 -TLSv1.1

Then in httpd.conf we uncomment
`LoadModule ssl_module libexec/apache24/mod_ssl.so`

Restart apache and volia, Diladele over HTTPS.

Further options that would be beneficial

    Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
    Header always set X-Frame-Options DENY
    Header merge Cache-Control no-store env=NO_STORE
    Header merge Pragma no-cache
    Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure

    TraceEnable off

**Comment by ra-at-diladele-com** [comment]
Need to have it at least in the docs and IDEALLY in the installer

**Comment by ra-at-diladele-com** [comment]
Added as https://docs.diladele.com/faq/webui/https.html
