### ISSUE TITLE
Add support for Radius

### ISSUE THREAD

**Issue by henry-nicolas** [ra-at-diladele-com/qlproxy_external#1288]
Dear,

Could you please add radius support to the Diladele web interface?
Apparently Radius is supported by Squid directly (see http://wiki.squid-cache.org/ConfigExamples/Authenticate/Radius).

So it could help with the integration of Diladele Qlproxy in environments that use Radius for their access authorizations. In my case; we are using Diladele in a docker container on Synology NAS (SME environment) so the users are managed locally on the NAS without LDAP servers but WiFi authentication is done through Radius.

Best regqrds,

**Comment by henry-nicolas** [comment]
Anything new on this ? I'v seen new wizard getting created for LDAP/AD/NTLM, Radius is quite popular in Enterprise world so it would be interesting to get it as well.

**Comment by ra-at-diladele-com** [comment]
In 6.0 already.
