### ISSUE TITLE
PDF - float division by zero

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1298]
when clicked on report of the following types. The HTML report works correctly BTW

icap-categories-top-by-ips
icap-categories-top-by-users
icap-policies-top-by-users
icap-policies-top-by-ips
icap-users-detailed-blocked-by-domains

```
2016-05-12 21:44:15,808 float division by zero
Please contact support at support@diladele.com
```

**Comment by ea-at-diladele-com** [comment]
fixed. test needed.
