### ISSUE TITLE
Beta 4.5.0.8CEF missing pdf.pdf_generator pfSense 2.3_1

### ISSUE THREAD

**Issue by QQHeresATissue** [ra-at-diladele-com/qlproxy_external#1304]
> ImportError at /accounts/login/
No module named pdf.pdf_generator
Request Method:	GET
Request URL:	https://host:8080/accounts/login/
Django Version:	1.6.11
Exception Type:	ImportError
Exception Value:	
No module named pdf.pdf_generator
Exception Location:	/opt/qlproxy/var/console/report/views.py in <module>, line 25
Python Executable:	/usr/local/bin/python
Python Version:	2.7.11
Python Path:	
['/opt/qlproxy/var/console',
 '/usr/local/lib/python2.7/site-packages/django_reportview-0.1-py2.7.egg',
 '/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-freebsd10',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/site-packages']

I installed reportlab via the following:

` #!/bin/tcsh`

` # in pfsense 2.3 a lot of packages were removed from default repository`
`setenv REPOURL http://pkg.freebsd.org/freebsd:10:x86:64/release_3/All`

`pkg add $REPOURL/jpeg-turbo-1.4.2.txz`
`pkg add $REPOURL/freetype2-2.6.2.txz`
`pkg add $REPOURL/xproto-7.0.28.txz`
`pkg add $REPOURL/fontconfig-2.11.1_1,1.txz`
`pkg add $REPOURL/renderproto-0.11.1.txz`
`pkg add $REPOURL/kbproto-1.0.7.txz`
`pkg add $REPOURL/libXdmcp-1.1.2.txz`
`pkg add $REPOURL/libpthread-stubs-0.3_6.txz`
`pkg add $REPOURL/libXau-1.0.8_3.txz`
`pkg add $REPOURL/libxcb-1.11.1.txz`
`pkg add $REPOURL/libX11-1.6.3,1.txz`
`pkg add $REPOURL/libXrender-0.9.9.txz`
`pkg add $REPOURL/libXft-2.3.2_1.txz`
`pkg add $REPOURL/tcl86-8.6.4.txz`
`pkg add $REPOURL/xextproto-7.3.0.txz`
`pkg add $REPOURL/libXext-1.3.3_1,1.txz`
`pkg add $REPOURL/scrnsaverproto-1.2.2.txz`
`pkg add $REPOURL/libXScrnSaver-1.2.2_3.txz`
`pkg add $REPOURL/tk86-8.6.4.txz`
`pkg add $REPOURL/py27-tkinter-2.7.11_6.txz`
`pkg add $REPOURL/py27-pillow-2.9.0_1.txz`
`pkg add $REPOURL/libfontenc-1.1.3.txz`
`pkg add $REPOURL/mkfontscale-1.1.2.txz`
`pkg add $REPOURL/mkfontdir-1.0.7.txz`
`pkg add $REPOURL/adobe-cmaps-20051217_3.txz`
`pkg add $REPOURL/py27-reportlab-3.0_2.txz`

Still no joy.

**Comment by ra-at-diladele-com** [comment]
will take a look now

**Comment by ra-at-diladele-com** [comment]
Fixed in the next published build (may 15)
