### ISSUE TITLE
Beta 4.5.0.1FD2 does not contain settings.*.json, and improperly detects as freebsd10 on pfSense 2.3_1

### ISSUE THREAD

**Issue by QQHeresATissue** [ra-at-diladele-com/qlproxy_external#1315]
Copying settings from previous beta works, but supplies improper paths.  In pfsense 2.3_1 the following paths are used:

>         "squid_exe_path":"/usr/local/sbin/squid",

>         "squid_conf_path":"/usr/local/etc/squid/squid.conf",

However the application still attempts to look in the old location and displays the following error:

> [Errno 2] No such file or directory: '/usr/pbi/squid-i386/etc/squid/squid.conf'

> Path to Squid configuration as detected by the application	/usr/pbi/squid-i386/etc/squid/squid.conf

**Comment by ra-at-diladele-com** [comment]
The 4.5 works with one single fle /opt/qlproxy/etc/system.json. Each package for each os gets correct one. Your installation seem to contain parts of previous installations. 

Please reinstall. Please do run "rm -Rf /opt/qlproxy" after uninstall to get rid of all dangling files.
