### ISSUE TITLE
Beta 4.5.0.1FD2 dashboard displays "Squid Proxy - Error" on pfSense 2.3_1

### ISSUE THREAD

**Issue by QQHeresATissue** [ra-at-diladele-com/qlproxy_external#1316]
The dashboard page give an error, and the data is partially complete.  Processes are not displayed, nor are active proxy clients.

![qlproxy_squid_error](https://cloud.githubusercontent.com/assets/11380639/15276283/1b166054-1aa9-11e6-9e0b-2959561dd202.png)

Possibly due to the following:

> root    63850   0.0  0.5  66108 19256  -  Is    2:05PM     0:00.01 /usr/local/sbin/squid -f /usr/local/etc/squid/squid.conf

> squid   64228   0.0  1.1 143916 46156  -  S     2:05PM     0:02.77 (squid-1) -f /usr/local/etc/squid/squid.conf (squid)

**Comment by ra-at-diladele-com** [comment]
Strange, I do not have this error. See attached screenshot. Could you please reinstall the qlproxy package? First remove as in http://docs.diladele.com/administrator_guide_4_5/install/freebsd10/remove.html; then reboot pfsense; add qlproxy user and group again and then install. 

![squid_pfsense](https://cloud.githubusercontent.com/assets/2544598/15281194/226d0764-1b39-11e6-9dc3-73d21ee89b64.png)
