### ISSUE TITLE
Typo in filtering / adblock settings page

### ISSUE THREAD

**Issue by m4t5** [ra-at-diladele-com/qlproxy_external#1340]
"Adsvertisements" should be "Ads" or "Advertisements" in

var/console/www/templates/qlproxy/ruleads_form.html:                

<label class="checkbox inline">{{form.block_ads}} Block Excessive Web Adsvertisements. Block requests for well-known web ads and ad networks. Block flash and introductory ads in YouTube.</label>

**Comment by ra-at-diladele-com** [comment]
fixed in 4.6 alpha
