### ISSUE TITLE
We need to write additional info Membership to the monitoring channel

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1342]
this will let us see what group of ad for example triggered selection of a given policy and later build specific report for a group and not for the whole policy

**Comment by ra-at-diladele-com** [comment]
the membership value that triggered selection of policy is now written to GUID.monitor for each ICAP transaction. Need to add it to the database and make reporting with conditions on this value.

**Comment by ra-at-diladele-com** [comment]
please implement upload into monitoring database and reassign the bug to me to implement limitations in the Web UI. Then we need to implement these limits in reporting.

**Comment by ra-at-diladele-com** [comment]
To 4.8?

**Comment by ea-at-diladele-com** [comment]
Moving to 4.8

**Comment by ea-at-diladele-com** [comment]
4.9

**Comment by ra-at-diladele-com** [comment]
is now at https://github.com/diladele/websafety-issues/issues/9
