### ISSUE TITLE
wsmgrd need to write to log on INFO after logs were rotated

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1343]
when reload signal is recieved; wsmgrd stops logging, starts logging and writes:

- reload completed successfully.
this will let us see that reload after logrotate was completed ok

**Comment by ea-at-diladele-com** [comment]
need to test.

**Comment by ra-at-diladele-com** [comment]
does not seem to work, but it seems to be incorrect idea anyway. closing...
