### ISSUE TITLE
Shall we NOT write clean ICAP requests?

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1357]
There will definitely be a response coming after clear request; so what for to write it?

**Comment by ra-at-diladele-com** [comment]
The ICAP server needs to write requests -> but wsmgrd DOES NOT write it into persistent sink.
In memory sync NEED to have these requests!

**Comment by ea-at-diladele-com** [comment]
Moving to 4.8

**Comment by ea-at-diladele-com** [comment]
needs testing.

**Comment by ra-at-diladele-com** [comment]
Question - if we now skip cleaned requests to Google for example - but we parse the search terms for Google to be represented in reports later from such requests - does it mean the report will be empty?

Or better rephrased - where to we get the search term report from - and may be it shall not be skipped?

**Comment by ra-at-diladele-com** [comment]
UPDATE: we need to explicitly check that the filtered out, "CLEAN" request is not used in "user search queries" report. And if it *is* used - still write it to the database.

**Comment by ea-at-diladele-com** [comment]
should be corrected.
