### ISSUE TITLE
Reports need to be sent by e-mail

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1407]

**Comment by ra-at-diladele-com** [comment]
Implemented the following changes in Web UI for this:
* Added new tab 'SMTP connector' in Web UI / Monitoring / Settings
* Each report template now has a field 'send the report to the following e-mails after generation'

Please check if this is ok for golang code and return the bug to start testing.

**Comment by ea-at-diladele-com** [comment]
now each job has its own list of emails

**Comment by ra-at-diladele-com** [comment]
Strange - does not work actually; I do not see email in inbox. And nothing in the logs.
Shall we at least write to log that *e-mail was sent* or *could not send email* ?

**Comment by ea-at-diladele-com** [comment]
Test needed, but not on squid reports for now. Please try other reports

**Comment by ra-at-diladele-com** [comment]
The SMTP settings seem to be correct; log record indicate e-mail was sent without error - but I do not see email in the target inbox. May it be error is still there but it is not shown in log because send operation runs async?

**Comment by ra-at-diladele-com** [comment]
I now have the python test client that works - the same info from Web UI using golang - does not work.

**Comment by ea-at-diladele-com** [comment]
Test needed

**Comment by ra-at-diladele-com** [comment]
does not work. creds are OK for sure
```
[7406] [2016-Oct-06 10:50:00.125] [reporting] [INFO] Sending email to 'BLABLA'
[7406] [2016-Oct-06 10:50:10.287] [reporting] [ERROR] Could not send an alert email, reason 504 5.7.4 Unrecognized authentication type
```

**Comment by ea-at-diladele-com** [comment]
needs testing. better not only with office365 but other smtp server just to make sure it works in general.

**Comment by ra-at-diladele-com** [comment]
works with office365
