### ISSUE TITLE
Generate folders on disk for reports not based on user name but based on id

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1409]
because now we have to sanitize user names to be present in the URL.

**Comment by ea-at-diladele-com** [comment]
test needed. please test ALL reports. a lot of changes. please generate pdf for ALL of them. easiest - build a database. then create all reports. then run a batch file that simply calls report.exe -id="xxxx" for all of the created reports. check the output with search that there are no errors or failures. and pdf files exists

**Comment by ra-at-diladele-com** [comment]
ok seems to work
