### ISSUE TITLE
Shall we move ubuntu.diladele.com to ubuntu14.diladele.com?

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1437]

**Comment by ra-at-diladele-com** [comment]
After a year when repo for currently released 4.6 is no longer needed.

**Comment by elico** [comment]
What exactly is the issue?
in any case you can use different subfolders for a repo, am I wrong?

**Comment by ra-at-diladele-com** [comment]
Hello Eliezer, 
It was just a note to ourselves - we have ubuntu16.diladele.com to keep a repo for ubuntu 16. The previous repo for ubuntu 14 was called ubuntu.diladele.com. So just renaming in order to be consistent... 

We actually use reprepro for repo .. having two different subdomains for different ubuntu versions allows us to keep the binaries cleanly separated, but ads more admin headaches :(

**Comment by elico** [comment]
Well it's a simple enough task so it's not a big headaches like I have:
OpenSUSE(2-4 versions)
CentOS
Ubuntu
Debian
.... and couple others.
