### ISSUE TITLE
Get rid of IPs table in the Monitoring

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1442]
We currently have Users and IPs tables in the Web UI and deep in the monitoring module.
We need to have ONLY users. If user name that comes from Squid is empty thus it means admin did not enable user authentication - in this case we need to use IP address information provided by Squid as User Name.

Please note if 'Reverse resolve DNS name' is checked in the Web UI then we need to apply the following algorithm:

```
user_name = <what squid gives us as user name>
if user_name.empty() {
      user_name = <what squid gives us as user ip>
      if should_resolve_dns {
            resolved_user_name = reverse_resolve_dns(user_name)
            if not resolved_user_name.empty() {
                   user_name = resolved_user_name
            }
      }
}
```

This will make our Reporting more understandable. 
If no objections - please reassign the bug and I will make changes in the Web UI. Then changes in golang need to be done.

**Comment by ea-at-diladele-com** [comment]
Need testing. Both ui and go changes in the same commit.

**Comment by ra-at-diladele-com** [comment]
OK in Surfing Now seems to be correct
