### ISSUE TITLE
Web Activity User Report - incorrect domain (only HTTPS:)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1457]
![https](https://cloud.githubusercontent.com/assets/2544598/19016718/cadc3144-8822-11e6-96bd-fca3b0a659b5.png)

**Comment by ea-at-diladele-com** [comment]
need testing

**Comment by ra-at-diladele-com** [comment]
seems gone, closing
