### ISSUE TITLE
Need to somehow collapse users in reports

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1496]
Due to various AD helpers we may have users like:

```
john.rambo@EXAMPLE.LAN
john.rambo@example.lan
john.rambo
```

in reports - but it is the same user actually. We need to collapse it to one (at lease first two types).

**Comment by ea-at-diladele-com** [comment]
need testing.

**Comment by ra-at-diladele-com** [comment]
Ok seems to work; need to browse and see if the reports only contain one type of user
