### ISSUE TITLE
Both UserName and UserIP need to be in Surfing Now (NOT in History!)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1657]
We removed it previously because we needed to have only User Name in reports (when no user name was available we used User IP as User Name).

But it is actually needed for reports only. In SurfingNow and SurfingHistory we MUST see both User IP and User Name.

**Comment by ea-at-diladele-com** [comment]
need testing.

**Comment by ra-at-diladele-com** [comment]
UserIP is still empty.

**Comment by ea-at-diladele-com** [comment]
need testing

**Comment by ra-at-diladele-com** [comment]
Seems to work fine
