### ISSUE TITLE
Web UI: need gui for clustering

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1673]
client.json 
{
    "enabled": true, 
    "port": 18999, 
    "server_address": "127.0.0.1", 
    "sync_interval": 5
}

server.json
{
    "enabled": false, 
    "port": 18999, 
    "server_address": "127.0.0.1"
}

Leave config.json in etc/ (see how it is generated in profile)

**Comment by ra-at-diladele-com** [comment]
Done, please test and tell when integration tests can be run.

**Comment by ea-at-diladele-com** [comment]
please run. it is also possible to ask information about nodes similar to monitoring dashboard at
127.0.0.1:18888/cluster/nodes

**Comment by ra-at-diladele-com** [comment]
GUI seems to work fine. Closing the ticket.
