### ISSUE TITLE
User Name collapsing MUST be done per channel

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1678]
Currently we collapse user names from:

user.name@DOMAIN.LAN (typical in kerberos) 
user.name (typical in ntlm)

to just user.name globally.

It would be nice to have this setting per monitoring channel. For example, having NON collapsed names in Surfing Now lets us immediately see what auth scheme was used (kerberos logins look like user@EXAMPLE.LAN).

For future versions.

**Comment by ea-at-diladele-com** [comment]
we do not do this. reports do the same normalization as the rest (if specified - if not - not)

**Comment by ra-at-diladele-com** [comment]
ok one normalization setting for all channels is ok
