### ISSUE TITLE
Remove 'resolve_ip_as_user_name' from wsmgrd

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1686]
All this is now done in wsicapd daemon. No need to use resolve in traffic daemon. Please note user name normalization still needs to be do done. ONLY reverse resolve of IP address need to be thrown away/commented out.

**Comment by ea-at-diladele-com** [comment]
need testing.

**Comment by ra-at-diladele-com** [comment]
ok
