### ISSUE TITLE
Surfing Now - user name gets converted to lower case.

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1688]
In ICAP server and thus in *.monitor I see the ` "user name" : "User1" `, but in Surfing Now page it is for unknown reason `"user1"` (i.e. converted to lower case). 

This is incorrect. The user name part must be exactly how wsmgrd got it from wsicapd daemon.

May it be this is undesired side effect of user name normalization? 
The normalization for now is JUST throwing away the @EXAMPLE.LAN domain part. We should not lower case the user name. Nether in Surfing Now, nor in Surfing History.

Please see #1689 for normalization info

**Comment by ea-at-diladele-com** [comment]
need to test

**Comment by ra-at-diladele-com** [comment]
Seems to work fine
