### ISSUE TITLE
Web UI / Traffic / Settings / Normalized Names - use in wsmgrd

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1689]
We have added the following feature in Web UI / Traffic / Settings. It is called "Normalized User Names". When this checkbox is true, `user1@EXAMPLE.LAN` becomes `user1`.

The wsmrgd already does it - so just use the setting from `monitor.json` to enable/disable this behavior. By default it is enabled.

**Comment by ea-at-diladele-com** [comment]
need testing
