### ISSUE TITLE
option - If page is excluded from filtering, also exclude all pages it refers to

### ISSUE THREAD

**Issue by tgstyle** [ra-at-diladele-com/qlproxy_external#169]
Could this be reversed on a page per page basis in the exclusion list? So when you uncheck this option.

[] If page is excluded from filtering, also exclude all pages it refers to (recommended for better user experience).

Make it so each individual Exclusion has a way to reverse it only for that specific page?

**Comment by ra-at-diladele-com** [comment]
In was already done in 4.4 (policy / advanced)
