### ISSUE TITLE
No installer on FreeBSD 10 (pfSense 2.2)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#323]

**Comment by jbwiv** [comment]
Any update on FreeBSD 10/pfSense 2.2.2?

**Comment by ra-at-diladele-com** [comment]
Hello John, unfortunately not for now, we are working on better monitoring for 4.2

**Comment by ra-at-diladele-com** [comment]
Now all binaries are compiled with the README instructions - the installer is NOT yet present.

**Comment by ra-at-diladele-com** [comment]
Renamed the bug to indicate we now need only the installer

**Comment by ea-at-diladele-com** [comment]
The first version of the package for FreeBSD 10 is ready. Please test. wsmgrd integration is still needed

**Comment by ra-at-diladele-com** [comment]
Ok installer works - but a lot of other open issue remain. Still this bug is fixed.
