### ISSUE TITLE
Add Docker build

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#508]

**Comment by henry-nicolas** [comment]
Could you please kindly raise the priority of this issue?
I would like to be able to run it on a Synology NAS (currently using qlproxy with a license but on a plain Debian OS), which supports Docker.

It would be nice if the Docker image contained not only the Squid + Qlproxy binaries but also the Django management web interface :)

**Comment by ra-at-diladele-com** [comment]
Hello Henry,

The docker philosophy is about one service per container if I am not mistaken. Please also see the community efforts at https://groups.google.com/d/msg/quintolabs-content-security-for-squid-proxy/60-uXIyRBRU/ol7jLq8cx64J

Thanks,
Raf

**Comment by ra-at-diladele-com** [comment]
Henry - may I ask if you are able to help testing this docker/native Synology build if we decide to increase the priority?

**Comment by ra-at-diladele-com** [comment]
Please we need a proven tutorial for this

**Comment by ra-at-diladele-com** [comment]
Tutorial is published at http://docs.diladele.com/tutorials/docker/index.html. The bug is now closed.
