### ISSUE TITLE
No entries in Surfing Now

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#603]
1. Block e-commerce shopping
2. Add paypal.com to exclusions in ICAP
2. Go to PayPal.com
3. PayPal is rendered partially because it references paypalobjects.com which is in e-commerce shopping
4. Open Surfing Now - nothing is present - i.e. the CONNECT requests to paypalobjects.com should be blocked and visible in Surfin Now - they *are blocked* but NOT visible in Surfing Now

Unless the Surfing Now buffer gets reused as it can contain only 250 last responses...

**Comment by ra-at-diladele-com** [comment]
Planned wsmgrd.exe for 4.3

**Comment by ra-at-diladele-com** [comment]
Question - how to we specify the amount of last minutes to store the SurfingNow in-memory database? Or is it in wsmgr.json / realtime / limit_mb ?

Is the limit in MB or in minutes? Need to clarify to put into the docs.

**Comment by ea-at-diladele-com** [comment]
it is in the realtime
{
   limit_size_mb : X
   limit_time_min: Y
}

that means the db never exceeds X megabytes
and all records older than Y will be deleted.

If during Y timeframe the size of records will be more than X

then during the last Y minutes only first X mb of records will be written. The rest will be discarded.

**Comment by ea-at-diladele-com** [comment]
this has be fixed and pushed to develop as described above.

**Comment by ea-at-diladele-com** [comment]
please test

**Comment by ra-at-diladele-com** [comment]
Ok then need to test
