### ISSUE TITLE
Surfing Now should have column name filtering

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#700]

**Comment by ra-at-diladele-com** [comment]
Please take a look if this is possible to implement. The idea is that admin has the ability to click on the column name and see the usual table that is sorted by that column.

**Comment by ea-at-diladele-com** [comment]
Done, merged, please test in "develop"

**Comment by ra-at-diladele-com** [comment]
ok, bug we got #971
