### ISSUE TITLE
SSL WebUI - add Squid dst style exclusions valid (mostly) for transparent SSL Filtering

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#705]
Seems the exclusions can be done in Squid too. I.e the intercept rules divert all traffic to Squid and it EXLCUDES the lists of IP addresses from SSL Bump like:

Create file `/usr/local/squid/etc/dst.nobump` with the following contents
```
# BCC bypass
91.198.63.0/24
# Salyk bypass
212.154.165.148/32
# WU bypass
191.232.0.0/13
65.52.0.0/14
# Symantec bypass
195.215.221.99/32
195.215.221.104/32
213.248.114.172/32
213.248.114.173/32
213.248.114.174/32
213.248.114.175/32
77.67.22.168/32
77.67.22.171/32
77.67.22.173/32
213.248.114.171/32
```

add this to your squid .conf
```
acl dst_nobump dst "/usr/local/squid/etc/dst.nobump"
ssl_bump none dst_nobump
```

**Comment by ra-at-diladele-com** [comment]
Google Drive application uses network:
```
# Google Drive
74.125.201.0/24
```

**Comment by k2gremlin** [comment]
Apple Computers owns the entire Class A network 17.0.0.0/8. I added this to my no_bump file to allow iOS App Store.

#Apple Computers
17.0.0.0/8

**Comment by k2gremlin** [comment]
#LogMeIn - These IP ranges may need to be more refined. These are the 3 ranges I have encountered so far.
63.251.0.0/16
74.201.0.0/16
216.52.0.0/16

**Comment by ra-at-diladele-com** [comment]
Done, need to announce the alpha and test

**Comment by ra-at-diladele-com** [comment]
added to FAQ - http://docs.diladele.com/faq/squid/apple_app_store.html
