### ISSUE TITLE
Need ability to block ALL uncategorized sites

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#710]
Something line - if domain name cannot be categorized - block it all. This functionality is present in SquidGuard for example. Due to the very distributed nature of modern internet (thing CDN) the akamai for example or cloudfront are not categorized now - then _every_ big site would be rendered incorrectly...

**Comment by ra-at-diladele-com** [comment]
1. The most common CDN sites need to be categorized as CDN
2. It should be possible (but not recommended) to block the non categorized web sites – this creates safe environments where all sites that experts looked at.

**Comment by ra-at-diladele-com** [comment]
first need to do #113

**Comment by sherazmughal** [comment]
step by step instruction and procedure ???plz

**Comment by sherazmughal** [comment]
step by step instruction and procedure ???plz

**Comment by sherazmughal** [comment]
can you pls explain steps ..this thing is not clear

**Comment by ra-at-diladele-com** [comment]
done, need to be tested in 4.8
