### ISSUE TITLE
Mail the reports to a gives e-mail address?

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#723]
The admin will need to manually adjust the settings.py and allow for external connections to their mail server though :(

> It would be really nice to get an option to receive a weekly report with top users/domain, blocked site report and stuff like that. Some automated reporting so.

**Comment by ea-at-diladele-com** [comment]
added to the reports. Please see the explanation in the email.

**Comment by ra-at-diladele-com** [comment]
duplicate of #1407
