### ISSUE TITLE
Surfing History - now allows to filter by IID only

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#729]
Need extensive filtering by all fields.

**Comment by ra-at-diladele-com** [comment]
Currently surfing history shows the last 1000 records from the database without filtering. Actually filtering is ONLY possible using IID. 

We need to add the DROPBOX with the column name to search for and INPUTBOX for the searched string. When user could select for example - get me all records where HOSTNAME colum contains 'microsoft.com'.

**Comment by ea-at-diladele-com** [comment]
Now we can filter on incident, host, user, user ip, policy, module, verdict.
Please test
