### ISSUE TITLE
Shall we use UDP to directly dump monitoring data into reporting daemon?

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#734]

**Comment by ra-at-diladele-com** [comment]
it is just a note to ourselves - no need to implement anything prior to discussion

**Comment by ra-at-diladele-com** [comment]
not in 4.3

**Comment by ea-at-diladele-com** [comment]
should not. with slow reader - fast writer there should be some intermediate storage.
