### ISSUE TITLE
Allow 'resolving the IP' into host name for the Surfing Now page

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#766]
currently only IP and User Name are shown in the Surfing Now tab - these come from Squid. We also need to allow the 'resolve IP address' setting - so that also the host name is shown. This is very helpful in networks where host <-> IP association is fixed

**Comment by ra-at-diladele-com** [comment]
There should be a setting in `wsmgrd.json` section `monitoring` that should be named `resolve_ip_as_user_name` default value is false.

If this setting is true - then surfing record should try to resolve the passed in IP into a string using DNS and use this string as UserName. ONLY IF USER NAME is empty. 

Later this info will get into database and will be used when building reports.

**Comment by ea-at-diladele-com** [comment]
This is currently done in the "resolver". Please see the monitoring module.
THe json config was also enhanced with resolve_ip_as_user_name.
Please test. Thank you!

**Comment by ra-at-diladele-com** [comment]
works
