### ISSUE TITLE
Add to 4.2 reporting

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#775]
Is there a way to find out actual data amounts used by each client on a per domain level?

For example, IP address 10.1.1.1 consumed 2.2GB from facebook.com and uploaded 1.5GB to tumblr.com

**Comment by jfla011** [comment]
I would really like to see this feature too.

**Comment by ra-at-diladele-com** [comment]
In 4.2 there will be the Top 50 domains for a given IP report - from this report if you will be able to sort these domains per the amount of data downloaded from these domains. There is another request that ask for clear separation of upload/download - #833

**Comment by ra-at-diladele-com** [comment]
This bug is closed.
