### ISSUE TITLE
wsmgrd not started as daemon in FreeBSD

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#793]

**Comment by ra-at-diladele-com** [comment]
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-poudriere-build-system-to-create-packages-for-your-freebsd-servers

**Comment by ra-at-diladele-com** [comment]
FreeBSD now compiles correctly - proceed with bug.

**Comment by ra-at-diladele-com** [comment]
see also #848 - shall we also use the bootstrapper exe in FreeBSD?

**Comment by ra-at-diladele-com** [comment]
please add wsmgrd to installer - it is now missing

**Comment by ea-at-diladele-com** [comment]
have you tried the latest sources? I have added it yesterday ...

**Comment by ra-at-diladele-com** [comment]
Sorry will do now

**Comment by ea-at-diladele-com** [comment]
I think the documentation scripts are still missing a couple of lines related to wsmgrd, but it is another bug, please reassign that one to me.

**Comment by ra-at-diladele-com** [comment]
done; now testing this bug
