### ISSUE TITLE
wsmgrd not started as daemon in Windows

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#794]

**Comment by ra-at-diladele-com** [comment]
May be postponed till the next version if too complex to implement - please research.

**Comment by ea-at-diladele-com** [comment]
there is an external package that allows doing so
https://godoc.org/golang.org/x/sys/windows/svc

**Comment by ea-at-diladele-com** [comment]
I would prefer to lower the priority for now and move to 4.4. If we have time we will look into this in 4.3, but very probably not.

**Comment by ra-at-diladele-com** [comment]
moved to 4.4

**Comment by ra-at-diladele-com** [comment]
not valid any more; we do not have windows build
