### ISSUE TITLE
report uploader should not upload if disk space is less than N Mb

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#829]

**Comment by ra-at-diladele-com** [comment]
for now it dumps the info into log but does not take into account

**Comment by ra-at-diladele-com** [comment]
the idea is not to corrupt the sqlite database.
this setting should be configuable - by default - no database updates if less than 25 Mb is left on HDD

**Comment by ea-at-diladele-com** [comment]
is this responsibility of the monitor process? or better the deamon, so that if the size is < 25 mb, then do not even dump the monitoring messages, but simply discard them. it seems the logic belongs to the daemon, or am I missing something? Thank you!

**Comment by ea-at-diladele-com** [comment]
I mean currently we put everything to the monitoring folder. even if the reader (wsgmgr) will decide not to write this to the DB, it is still problematic because the service itself can exhaust the limit but just putting files into the dir. So I would propose to move this to the daemon instead.
