### ISSUE TITLE
Support for HTTPS, squid 3.4.8 on Raspberry PI for qlproxy 4.2 RC2

### ISSUE THREAD

**Issue by philburr** [ra-at-diladele-com/qlproxy_external#898]
I compiled squid 3.4.8 from wheezy backports on Raspberry PI 2 debian wheezy.  I enabled SSL support via --enable-ssl, --enable-ssl-crtd in debian/rules and build packages.  I then followed roughly the Debian 8 installation process on my RPi2, using the armhf packages I build instead and the appropriate RPi2 qlproxy package.

However, it appears that the RPi2 qlproxy package (qlproxy-4.2.0.F225_armhf.deb) lacks support for HTTPS interception.  Namely it lacks certain files:
/opt/qlproxy/etc/squid/squid.acl
/opt/qlproxy/etc/myca.pem

If it is possible please support HTTPS on RPi2.  If you would like a version of squid that supports SSL, I've made them available through dropbox:
https://www.dropbox.com/sh/6ngnls722g7ylr7/AACvgO0yx_Pys9kaX1orDo6ka?dl=0

**Comment by ra-at-diladele-com** [comment]
Hello Philiburr,

What makes you think HTTPS is not supported on RPI build? It should be supported. The Web UI detects if Squid is capable of HTTPS filtering and then generates the squid.acl file automatically after "Save and Restart" button is clicked.

May I ask for the screenshot of Web UI / Squid Proxy / Version tab? It describes Squid attributes detected by the application.

Thanks!

**Comment by philburr** [comment]
You are correct.  The file is autogenerated and performing the restart as you described generates the file.  The web interface does show HTTPS support.  When I didn't see the files referenced in the squid.conf configuration I assumed things were missing.

Thanks for your assistance.
