### ISSUE TITLE
wsmgr_monitor.json - has configurable reference to monitor folder

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#909]
it should use predefined folders as follows:
- /opt/qlproxy/var/monitor - as a folder to look for *.monitor files from qlproxyd

this should NOT be configurable in a JSON file - just hardcoded

**Comment by ra-at-diladele-com** [comment]
please use the folders.go code to get the VAR folder

**Comment by ea-at-diladele-com** [comment]
should be fixed now, please have a look. Thank you!

**Comment by ra-at-diladele-com** [comment]
ok
