### ISSUE TITLE
wsmgrd.exe needs to fully reload all its configuration on SIGHUP

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#912]

**Comment by ea-at-diladele-com** [comment]
This is currently done, but only on Linux. could you please try it out? Thank you! (only the http rest listener uses the same port, you have to restart in order to reload it)

**Comment by ea-at-diladele-com** [comment]
right now we do not support the custom port for http rest server endpoint. should we also parameterize it? should we also put everything into one file, like wsgmon.json ?

**Comment by ra-at-diladele-com** [comment]
yes please see #919. This bug is now in testing and does not need any other comments. I will close it after testing and will open another one for Windows (SIGHUP is not supported on that platform).

**Comment by ra-at-diladele-com** [comment]
Still waiting for #965. Currently after SIGHUB wsmgr exists - which is a serious error.

**Comment by ea-at-diladele-com** [comment]
965 is fixed. please have a look at this one again.

**Comment by ra-at-diladele-com** [comment]
Ok seems to work
