### ISSUE TITLE
wsmgrd.exe needs to close and open log file on SIGHUP

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#913]
(this is needed for logrotate)

**Comment by ea-at-diladele-com** [comment]
should be reload the log file now. at least on Linux. could you please try it out? thank you!

**Comment by ra-at-diladele-com** [comment]
waiting for #965 - for now the wsmgrd exits after reload

**Comment by ea-at-diladele-com** [comment]
could you please see now? Thank you!

**Comment by ra-at-diladele-com** [comment]
ok seems to work
