### ISSUE TITLE
4.2.0.CBF4 don't intercept all .exe

### ISSUE THREAD

**Issue by llevet** [ra-at-diladele-com/qlproxy_external#917]
Hi,

I can download this url : http://the.earth.li/~sgtatham/putty/0.65/x86/putty.exe
But the other files exe are blocked : http://the.earth.li/~sgtatham/putty/0.65/x86/

Why i can download this exe file ????

Ludo.

**Comment by ra-at-diladele-com** [comment]
Hello llevet,

We use Content Disposition to get the file name being downloaded. Unfortunately HTTP(S) protocol operates in terms of byte streams, not files - that is why not all web servers set this header. If you'd like to harden your installation - then it is advisable to also block by file type as explained in http://docs.diladele.com/administrator_guide_4_2/configuring_policies/blocking_file_downloads.html

**Comment by llevet** [comment]
Hi,

It ever the case, All files type exe are in default filter but i can donwload the file : http://the.earth.li/~sgtatham/putty/0.65/x86/putty.exe
And squid identify well the file as executable :
TCP_MISS/200 270362 GET http://the.earth.li/~sgtatham/putty/0.65/x86/putty.exe - HIER_NONE/- application/x-msdos-program

So i don't understand why is not detected !

Ludo.

**Comment by ra-at-diladele-com** [comment]
Hello llevet,

I have tried on the latest version and everything you mentioned seems to be blocked. It might be your browser or squid cached this file after it was downloaded first time and later our application did not even see the contents of this file.
