### ISSUE TITLE
The monitor2.sqlite must also be copied to monitor2.sqlite.default in the source tree

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#925]
after regeneration of monitor2.sqlite please also create a copy of it named monitor2.sqlite.default - this is needed to have the default database to easy reset the monitoring database as asked by the users - see http://docs.diladele.com/administrator_guide_4_2/traffic_monitoring/database/sqlite.html

**Comment by ea-at-diladele-com** [comment]
should be fixed now. please check

**Comment by ra-at-diladele-com** [comment]
ok
