### ISSUE TITLE
Both connection strings need to be in wsmgrd.json

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#933]
Currently we have

```
         "persistent" : 
        {
            "driver" : "sqlite3"
        },
```

in the wsmgrd.json file. When admin needs to switch to MySQL he will need to search documentations on how to do it - this is not convinient. I propose:

```
 "monitoring": { bla bla
        "persistent" :  {
             "active" : "sqlite3",
            "sqlite" : { bla bla },
           "mysql" : {bla bla}
    },


```

This will let admin check the mysql settings, adjust them if needed and then activate

**Comment by ea-at-diladele-com** [comment]
currently we cannot specify anything for SQLite. so it will be simply

for sqlite
 "monitoring": { bla bla
        "persistent" :  {
             "active" : "sqlite",
           "mysql" :"connectionstring..."
    },


or for mysql

 "monitoring": { bla bla
        "persistent" :  {
             "active" : "mysql",
           "mysql" : "connectionstring..."
    },

**Comment by ea-at-diladele-com** [comment]
should be fixed now.

**Comment by ea-at-diladele-com** [comment]
please test
