### ISSUE TITLE
wsmgrd: top level domain is parsed incorrectly (reversed order)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#936]
Host	diladele.zendesk.com
Top Level Domain	com.zendesk

**Comment by ea-at-diladele-com** [comment]
This one is fixed now.

THe corresponding question - currently we are not really finding the top level domain, just getting the last two elements of the host part of the url.

we can use some library to get the real top level domain, i.e.https://github.com/golang/net/

**Comment by ea-at-diladele-com** [comment]
I have added to use net/x/publicsuffix
if it does not succeeed I try to do the last to . elements.

**Comment by ea-at-diladele-com** [comment]
Please test

**Comment by ra-at-diladele-com** [comment]
done correctly
