### ISSUE TITLE
wsmgrd: after upload into persistent storage date and time seem to be invalid

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#937]
![image](https://cloud.githubusercontent.com/assets/2544598/9406038/431662a4-47fd-11e5-9a46-3e6d79ca9d9e.png)

Also when you click on an event the date time field is also invalid

![image](https://cloud.githubusercontent.com/assets/2544598/9406065/6fed4298-47fd-11e5-971f-bfc055c983f6.png)

**Comment by ea-at-diladele-com** [comment]
Should be fixed now.

**Comment by ea-at-diladele-com** [comment]
Please test

**Comment by ra-at-diladele-com** [comment]
Fixed
