### ISSUE TITLE
Surfing History - Provide a REST interface to browser record list (paginated) and individual record

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#940]
The Surfing History interface is now done in Django (see attach)
The UI now needs to be done in Angular JS that calls for the actual JSON contents into REST interface of wsmgrd.

![image](https://cloud.githubusercontent.com/assets/2544598/9406912/d6280b5e-4804-11e5-97ba-c57e455b75ce.png)

**Comment by ra-at-diladele-com** [comment]
next in 4.4

**Comment by ea-at-diladele-com** [comment]
Probably not in 4.4?

**Comment by ra-at-diladele-com** [comment]
now at https://github.com/diladele/websafety-issues/issues/298
