### ISSUE TITLE
Time in SurfingNow seems to be LocalTime in Surfing History - GMT?

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#964]

**Comment by ea-at-diladele-com** [comment]
Which should it be in both cases? UTC or Local?

**Comment by ra-at-diladele-com** [comment]
I presume local - in all cases.

**Comment by ea-at-diladele-com** [comment]
I cannot reproduce it:
This is what I see in surfing now
2015-09-01T12:17:45Z    830  
yhit is in history
Sept. 1, 2015, 12:17 p.m. (date: Sept. 1, 2015; time 12:17 p.m.; hour of day 12) 

looks kind of the same - 12:17. 

How can I reproduce the issue?
Thank you!

**Comment by ea-at-diladele-com** [comment]
I did it even look the same.

Could you check on a running icap whether it is still UTC or local? thank you!

**Comment by ra-at-diladele-com** [comment]
Done; localtime
