### ISSUE TITLE
SurfingNow - second click on column name should invert sort order

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#971]
1. Open Surfing Now
2. Click on Level - Surfing Now orders and shows Body as first 
3. Click on Level again - Nothing happens - BUT it should show Body as last

**Comment by ea-at-diladele-com** [comment]
this is done. 
the only problem is that the width of the column headers somehow changes. you have to fix this somewhere in the style I suppose. sorry, not gui guru :(
