### ISSUE TITLE
Web UI / Dashboard / Squid - add connection info

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#975]
```
	Number of HTTP requests received:	4381
	Average HTTP requests per minute since start:	202.2
```

**Comment by ra-at-diladele-com** [comment]
should be in `curl http://localhost:18888/monitoring/analytics/squid/info`

**Comment by ea-at-diladele-com** [comment]
Added the following fields to the json info

	HttpRequestsReceived               int
	AvgHttpRequestsPerMinuteSinceStart float64
