### ISSUE TITLE
Web UI / Dash / Squid - Active Proxy Clients

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#977]
- Move to Surfing Now (as a Squid tab)
- remove Local column 
- adjust Remote column to be IP (without port)
- rename User Name to User
- Age (seconds) should be int and not float as now
- URL - cache_object:// should not be present (filter it out)
- get host name from URL 
- add 'Recently ended connections - 30 seconds' view
- add 'Recently ended connections - 1 minute' view

**Comment by ra-at-diladele-com** [comment]
Please first do in `curl http://localhost:18888/monitoring/analytics/squid/connections`

- remove Local column
- adjust Remote column to be IP (without port)
- Age (seconds) should be int and not float as now
- URL - cache_object:// should not be present (filter it out)
- get host name from URL

Then I do in web UI (MAY BE IN 4.4)
- Move to Surfing Now (as a Squid tab)
- add 'Recently ended connections - 30 seconds' view
- add 'Recently ended connections - 1 minute' view

**Comment by ea-at-diladele-com** [comment]
By the way it is not 
 curl http://localhost:18888/monitoring/analytics/squid/connections 

it is
 curl http://localhost:18888/monitoring/analytics/squid/active_requests

**Comment by ea-at-diladele-com** [comment]
The following is done:
 - Local removed
 - Remote column is IP without port
 - Age (start and secondsago) are both int64 now
 - all urls starting with cache_object:// are filtered out
 - Host field is added


To tell the truth golang does not support nice parsing of urls somehow if the schema is not present. So maybe it makes sense to parse this on the JS side from URI if JS provides more libraries for this.

Just try using Host field for now and see whether it fits your needs. if not - better do parsing in js then.

**Comment by ra-at-diladele-com** [comment]
Yes hostname is better parsed on the JS side, please remove it from output.

**Comment by ra-at-diladele-com** [comment]
Done
