### ISSUE TITLE
Memory of wsmgrd is not being released

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#980]
Use Apache Benchmark tool to stress the Squid+ICAP.
```
ab -c 50 -n 10000 -X 192.168.178.33:3128 http://185.72.231.31/
```

memory usage of wsmgrd goes to 700MB (btw when benchmark is done - the CPU usage of wsmgrd is maxed out! - squid and qlproxyd are moderate).

**Comment by ea-at-diladele-com** [comment]
Could you please perform this test now? Thank you! It should be ok more or less now.

**Comment by ra-at-diladele-com** [comment]
Yes this is much better, closing the bug
