### ISSUE TITLE
DB: - it should be possible/configurable NOT to save query_params into database

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#983]
Please tell me if this is possible - if yes I will make a setting in monitoring.json for this

**Comment by ea-at-diladele-com** [comment]
does it mean some reports won't work properly?

**Comment by ra-at-diladele-com** [comment]
yes in principle, but for now we do not have reports over /path/in/url?or=query&parameters=
so for 4.3 I think this is acceptable to have it disabled by default - this will make size of the database much smaller

**Comment by ea-at-diladele-com** [comment]
what should be the name of the field in monitor.json?

**Comment by ra-at-diladele-com** [comment]
store_query per channel

**Comment by ea-at-diladele-com** [comment]
done
