### ISSUE TITLE
Remove from Access Log and SysLog (and from monitor.json)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#989]
Store URL path into access log. Disabled by default.
Store URL query into access log. Disabled by default.

**Comment by ra-at-diladele-com** [comment]
No please implement - in Squid it is possible to NOT save the query in syslog/access log - so we must do the same. And as for path - let's leave it also here as it may potentially limit the amount of info qlproxyd needs to write.

**Comment by ea-at-diladele-com** [comment]
Should work properly now

**Comment by ra-at-diladele-com** [comment]
Ok I see it is working - but I would like to get the full URL in access log (possibly without paths and query strings) and not the 
```
<domain name> <path> <query>
```

**Comment by ra-at-diladele-com** [comment]
For now it is not clear if we should revert writing to access.log from qlproxyd...

**Comment by ra-at-diladele-com** [comment]
Let's rethink after #62

**Comment by ra-at-diladele-com** [comment]
Ok implemented; closing
