### ISSUE TITLE
Real Time - Timestamp must be in localtime (like in History???)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#994]
in db it all stored in UTC

**Comment by ea-at-diladele-com** [comment]
could you please check now? I changed this in the html template so not sure if this fixed it.

**Comment by ra-at-diladele-com** [comment]
I am checking now:
- the date command in console gives 22:47
- on Surfing Now I see 08:47 pm
- on Surfing History I see 07:47 

Something is wrong.
I would like to see 'LOCALTIME' everywhere. Shall we also store the LOCALTIME in the database???

**Comment by ea-at-diladele-com** [comment]
should be fixed properly now. please test.
now everything is UTC, only what the user see is taken from TIME_ZONE specified in the settings.

There could be some problems with reports, but this should be tested differently.

**Comment by ra-at-diladele-com** [comment]
Ok seems to work correctly
